//! BCH(31,21) + even-parity error-control code used by every FLEX 32-bit word.
//!
//! # Spec provenance
//!
//! Motorola **FLEX** is a one-way paging air-interface; its on-air error
//! control is documented in the FLEX protocol specification (the same code is
//! reproduced by every public FLEX reference, e.g. multimon-ng's
//! `demod_flex.c` and the "FLEX paging protocol" descriptions derived from
//! Motorola's *FLEX Protocol — Technical Summary* / TIA/EIA refs).
//!
//! Each 32-bit FLEX word, **as oriented for the error check**, is:
//!
//! ```text
//!   bit 0  .. bit 20  (21 bits) : information / data bits
//!   bit 21 .. bit 30  (10 bits) : BCH(31,21) check bits
//!   bit 31            (1 bit)   : even parity over bits 0..=30
//! ```
//!
//! The 31 low bits form a **BCH(31,21)** code generated by the primitive
//! polynomial
//!
//! ```text
//!   g(x) = x^10 + x^9 + x^8 + x^6 + x^5 + x^3 + 1
//! ```
//!
//! whose 11 coefficients x^10..x^0 are `1 1 1 0 1 1 0 1 0 0 1` = **0x769**.
//! This is the identical BCH(31,21,2) used by POCSAG (CCIR Radiopaging Code
//! No.1 / ITU-R M.584); FLEX reuses it. It corrects up to **2** bit errors over
//! the 31 protected bits, detecting more. (See multimon-ng `demod_flex.c`
//! `bch_3121_*` and the FLEX protocol BCH definition.)
//!
//! IMPORTANT bit-ordering note: FLEX words are transmitted **LSB-first** on
//! air, and the FLEX literature usually presents words with the data in the
//! LOW bits (bit 0 = first/least-significant data bit). That is the opposite of
//! the POCSAG convention (flag in the MSB). This module therefore keeps the
//! FLEX-native orientation: data in bits 0..=20, check in 21..=30, parity in
//! bit 31. All the framing code in [`crate::frame`] reads fields from this same
//! orientation.

/// BCH(31,21) generator polynomial coefficients x^10..x^0 = 0x769.
/// (FLEX protocol error-control; identical generator to ITU-R M.584 POCSAG.)
pub const BCH_POLY: u32 = 0x769;

/// Number of information bits per FLEX word.
pub const DATA_BITS: u32 = 21;

/// Compute the BCH syndrome over the 31 protected bits (bits 0..=30) of a FLEX
/// word, in FLEX (data-in-low-bits) orientation.
///
/// To reuse a single MSB-first long-division kernel we map the FLEX layout onto
/// a 31-bit polynomial whose degree-30 coefficient is data bit 0. We compute the
/// remainder of the 31-bit word (excluding the parity bit 31) divided by g(x).
/// Zero ⇔ the 31 bits are a valid BCH codeword.
pub fn syndrome(word: u32) -> u32 {
    // Reflect the low 31 bits so data bit 0 becomes the polynomial's highest
    // term; division is then a plain MSB-first reduction by g(x).
    let mut acc = reflect31(word & 0x7FFF_FFFF);
    for bit in (10..31).rev() {
        if acc & (1 << bit) != 0 {
            acc ^= BCH_POLY << (bit - 10);
        }
    }
    acc & 0x3FF
}

/// Reflect the low 31 bits of `v` (bit i <-> bit 30-i).
fn reflect31(v: u32) -> u32 {
    let mut out = 0u32;
    for i in 0..31 {
        if v & (1 << i) != 0 {
            out |= 1 << (30 - i);
        }
    }
    out
}

/// Even parity over the low 31 bits (bits 0..=30). FLEX uses even parity: the
/// parity bit (bit 31) is chosen so the total number of 1s across all 32 bits
/// is even.
pub fn parity_bit(word_31: u32) -> u32 {
    (word_31 & 0x7FFF_FFFF).count_ones() & 1
}

/// True iff `word` is a structurally valid FLEX word: BCH syndrome zero over
/// bits 0..=30 and overall even parity (all 32 bits).
pub fn is_valid(word: u32) -> bool {
    syndrome(word) == 0 && (word.count_ones() & 1) == 0
}

/// Systematically encode 21 data bits (in the low 21 bits) into a full 32-bit
/// FLEX word: BCH(31,21) check bits in 21..=30, even parity in bit 31.
pub fn encode(data21: u32) -> u32 {
    let data21 = data21 & 0x1F_FFFF;
    // Place the 21 data bits in the low positions; find the 10 check bits that
    // make the 31-bit word a BCH codeword. Reuse the MSB-first kernel on the
    // reflected layout: data bit 0 maps to polynomial degree 30, so its check
    // bits land in reflected positions 0..=9 = FLEX bits 21..=30.
    let reflected_data = {
        // Reflect 21 data bits into positions 30..=10 (high end).
        let mut r = 0u32;
        for i in 0..21 {
            if data21 & (1 << i) != 0 {
                r |= 1 << (30 - i);
            }
        }
        r
    };
    let mut rem = reflected_data;
    for bit in (10..31).rev() {
        if rem & (1 << bit) != 0 {
            rem ^= BCH_POLY << (bit - 10);
        }
    }
    // rem occupies the low 10 bits (reflected positions 0..=9). Reflect the
    // whole 31-bit codeword back to FLEX orientation.
    let codeword31_reflected = reflected_data | (rem & 0x3FF);
    let word31 = reflect31(codeword31_reflected);
    word31 | (parity_bit(word31) << 31)
}

/// Attempt to correct up to 2 bit errors in a received 32-bit FLEX word.
///
/// Returns `Some((corrected_word, bits_flipped))` if a valid word is within
/// Hamming distance 2 (including the parity bit), else `None`.
///
/// Brute-force syndrome decoding over the 31 protected bits (then the parity
/// bit is recomputed). For BCH(31,21,2) the candidate count is
/// 1 + 31 + 31·30/2 = 497 — cheap, exhaustive, and maximum-likelihood within
/// the code's distance.
pub fn correct(word: u32) -> Option<(u32, u32)> {
    if is_valid(word) {
        return Some((word, 0));
    }
    let base31 = word & 0x7FFF_FFFF;
    // Lone parity-bit error: BCH part already valid but overall parity wrong.
    if syndrome(word) == 0 {
        let full = base31 | (parity_bit(base31) << 31);
        return Some((full, (full ^ word).count_ones()));
    }
    // 1 error in the protected field.
    for i in 0..31 {
        let cand31 = base31 ^ (1 << i);
        if syndrome(cand31) == 0 {
            let full = cand31 | (parity_bit(cand31) << 31);
            return Some((full, (full ^ word).count_ones()));
        }
    }
    // 2 errors in the protected field.
    for i in 0..31 {
        for j in (i + 1)..31 {
            let cand31 = base31 ^ (1 << i) ^ (1 << j);
            if syndrome(cand31) == 0 {
                let full = cand31 | (parity_bit(cand31) << 31);
                return Some((full, (full ^ word).count_ones()));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_produces_valid_words() {
        for data in [
            0x0_0000u32,
            0x1_5555,
            0x0_AAAA,
            0x1F_FFFF,
            0x12_3456,
            0x0_0001,
        ] {
            let w = encode(data);
            assert!(
                is_valid(w),
                "encode({data:#x}) -> {w:#x} not a valid FLEX word"
            );
            // Systematic: the 21 low bits must equal the data.
            assert_eq!(
                w & 0x1F_FFFF,
                data & 0x1F_FFFF,
                "data bits altered by encode"
            );
        }
    }

    #[test]
    fn corrects_single_bit_error() {
        let w = encode(0x12_3456);
        for i in 0..32 {
            let corrupted = w ^ (1 << i);
            let (fixed, flips) = correct(corrupted).expect("must correct 1 error");
            assert_eq!(fixed, w, "bit {i}: did not recover original");
            assert_eq!(flips, 1, "bit {i}: expected exactly 1 correction");
        }
    }

    #[test]
    fn corrects_double_bit_error() {
        let w = encode(0x0A_5C3);
        let corrupted = w ^ (1 << 3) ^ (1 << 19);
        let (fixed, flips) = correct(corrupted).expect("must correct 2 errors");
        assert_eq!(fixed, w);
        assert_eq!(flips, 2);
    }

    #[test]
    fn rejects_uncorrectable_triple_error() {
        // 3 errors exceed BCH(31,21,2) distance; the decoder must not claim the
        // TRUE codeword as a <=2-error correction.
        let w = encode(0x1_2345);
        let corrupted = w ^ (1 << 1) ^ (1 << 14) ^ (1 << 28);
        if let Some((fixed, flips)) = correct(corrupted) {
            assert!(
                !(fixed == w && flips <= 2),
                "3-error pattern must not be correctable as the true word"
            );
        }
    }

    #[test]
    fn reflect_is_involution() {
        for v in [0u32, 1, 0x7FFF_FFFF, 0x2AAA_AAAA, 0x12345] {
            assert_eq!(reflect31(reflect31(v & 0x7FFF_FFFF)), v & 0x7FFF_FFFF);
        }
    }
}
