/// (element name, argument ASN.1 type, phraseology) by CHOICE index
/// — generated from docs/asn1/atn-cpdlc.asn (ICAO Doc 9880 module).
pub const UPLINK_ELEMENTS: [(&str, &str, &str); 238] = [
    ("uM0NULL", "NULL", "UNABLE"),
    ("uM1NULL", "NULL", "STANDBY"),
    ("uM2NULL", "NULL", "REQUEST DEFERRED"),
    ("uM3NULL", "NULL", "ROGER"),
    ("uM4NULL", "NULL", "AFFIRM"),
    ("uM5NULL", "NULL", "NEGATIVE Urg(N)/Alr(L)/Resp(N)"),
    ("uM6Level", "Level", "EXPECT [level] Urg(L)/Alr(L)/Resp(R)"),
    ("uM7Time", "Time", "EXPECT CLIMB AT [time]"),
    ("uM8Position", "Position", "EXPECT CLIMB AT [position]"),
    ("uM9Time", "Time", "EXPECT DESCENT AT [time]"),
    ("uM10Position", "Position", "EXPECT DESCENT AT [position]"),
    ("uM11Time", "Time", "EXPECT CRUISE CLIMB AT [time]"),
    ("uM12Position", "Position", "EXPECT CRUISE CLIMB AT [position]"),
    ("uM13TimeLevel", "TimeLevel", "AT [time] EXPECT CLIMB TO [level]"),
    ("uM14PositionLevel", "PositionLevel", "AT [position] EXPECT CLIMB TO [level]"),
    ("uM15TimeLevel", "TimeLevel", "AT [time] EXPECT DESCENT TO [level]"),
    ("uM16PositionLevel", "PositionLevel", "AT [position] EXPECT DESCENT TO [level]"),
    ("uM17TimeLevel", "TimeLevel", "AT [time] EXPECT CRUISE CLIMB TO [level]"),
    ("uM18PositionLevel", "PositionLevel", "AT [position] EXPECT CRUISE CLIMB TO [level]"),
    ("uM19Level", "Level", "MAINTAIN [level]"),
    ("uM20Level", "Level", "CLIMB TO [level]"),
    ("uM21TimeLevel", "TimeLevel", "AT [time] CLIMB TO [level]"),
    ("uM22PositionLevel", "PositionLevel", "AT [position] CLIMB TO [level]"),
    ("uM23Level", "Level", "DESCEND TO [level]"),
    ("uM24TimeLevel", "TimeLevel", "AT [time] DESCEND TO [level]"),
    ("uM25PositionLevel", "PositionLevel", "AT [position] DESCEND TO [level]"),
    ("uM26LevelTime", "LevelTime", "CLIMB TO REACH [level] BY [time]"),
    ("uM27LevelPosition", "LevelPosition", "CLIMB TO REACH [level] BY [position]"),
    ("uM28LevelTime", "LevelTime", "DESCEND TO REACH [level] BY [time]"),
    ("uM29LevelPosition", "LevelPosition", "DESCEND TO REACH [level] BY [position]"),
    ("uM30LevelLevel", "LevelLevel", "MAINTAIN BLOCK [level] TO [level]"),
    ("uM31LevelLevel", "LevelLevel", "CLIMB TO AND MAINTAIN BLOCK [level] TO [level]"),
    ("uM32LevelLevel", "LevelLevel", "DESCEND TO AND MAINTAIN BLOCK [level] TO [level]"),
    ("uM33NULL", "NULL", "Reserved"),
    ("uM34Level", "Level", "CRUISE CLIMB TO [level]"),
    ("uM35Level", "Level", "CRUISE CLIMB ABOVE [level]"),
    ("uM36Level", "Level", "EXPEDITE CLIMB TO [level]"),
    ("uM37Level", "Level", "EXPEDITE DESCENT TO [level]"),
    ("uM38Level", "Level", "IMMEDIATELY CLIMB TO [level]"),
    ("uM39Level", "Level", "IMMEDIATELY DESCEND TO [level]"),
    ("uM40NULL", "NULL", "Reserved"),
    ("uM41NULL", "NULL", "Reserved Urg(L)/Alr(L)/Resp(Y)"),
    ("uM42PositionLevel", "PositionLevel", "EXPECT TO CROSS [position] AT [level]"),
    ("uM43PositionLevel", "PositionLevel", "EXPECT TO CROSS [position] AT OR ABOVE [level]"),
    ("uM44PositionLevel", "PositionLevel", "EXPECT TO CROSS [position] AT OR BELOW [level]"),
    ("uM45PositionLevel", "PositionLevel", "EXPECT TO CROSS [position] AT AND MAINTAIN [level]"),
    ("uM46PositionLevel", "PositionLevel", "CROSS [position] AT [level]"),
    ("uM47PositionLevel", "PositionLevel", "CROSS [position] AT OR ABOVE [level]"),
    ("uM48PositionLevel", "PositionLevel", "CROSS [position] AT OR BELOW [level]"),
    ("uM49PositionLevel", "PositionLevel", "CROSS [position] AT AND MAINTAIN [level]"),
    ("uM50PositionLevelLevel", "PositionLevelLevel", "CROSS [position] BETWEEN [level] AND [level]"),
    ("uM51PositionTime", "PositionTime", "CROSS [position] AT [time]"),
    ("uM52PositionTime", "PositionTime", "CROSS [position] AT OR BEFORE [time]"),
    ("uM53PositionTime", "PositionTime", "CROSS [position] AT OR AFTER [time]"),
    ("uM54PositionTimeTime", "PositionTimeTime", "CROSS [position] BETWEEN [time] AND [time]"),
    ("uM55PositionSpeed", "PositionSpeed", "CROSS [position] AT [speed]"),
    ("uM56PositionSpeed", "PositionSpeed", "CROSS [position] AT OR LESS THAN [speed]"),
    ("uM57PositionSpeed", "PositionSpeed", "CROSS [position] AT OR GREATER THAN [speed]"),
    ("uM58PositionTimeLevel", "PositionTimeLevel", "CROSS [position] AT [time] AT [level]"),
    ("uM59PositionTimeLevel", "PositionTimeLevel", "CROSS [position] AT OR BEFORE [time] AT [level]"),
    ("uM60PositionTimeLevel", "PositionTimeLevel", "CROSS [position] AT OR AFTER [time] AT [level]"),
    ("uM61PositionLevelSpeed", "PositionLevelSpeed", "CROSS [position] AT AND MAINTAIN [level] AT [speed]"),
    ("uM62TimePositionLevel", "TimePositionLevel", "AT [time] CROSS [position] AT AND MAINTAIN [level]"),
    ("uM63TimePositionLevelSpeed", "TimePositionLevelSpeed", "AT [time] CROSS [position] AT AND MAINTAIN [level] AT [speed]"),
    ("uM64DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("uM65PositionDistanceSpecifiedDirection", "PositionDistanceSpecifiedDirection", "AT [position] OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("uM66TimeDistanceSpecifiedDirection", "TimeDistanceSpecifiedDirection", "AT [time] OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("uM67NULL", "NULL", "PROCEED BACK ON ROUTE"),
    ("uM68Position", "Position", "REJOIN ROUTE BY [position]"),
    ("uM69Time", "Time", "REJOIN ROUTE BY [time]"),
    ("uM70Position", "Position", "EXPECT BACK ON ROUTE BY [position]"),
    ("uM71Time", "Time", "EXPECT BACK ON ROUTE BY [time]"),
    ("uM72NULL", "NULL", "RESUME OWN NAVIGATION"),
    ("uM73DepartureClearance", "DepartureClearance", "[DepartureClearance]"),
    ("uM74Position", "Position", "PROCEED DIRECT TO [position]"),
    ("uM75Position", "Position", "WHEN ABLE PROCEED DIRECT TO [position]"),
    ("uM76TimePosition", "TimePosition", "AT [time] PROCEED DIRECT TO [position]"),
    ("uM77PositionPosition", "PositionPosition", "AT [position] PROCEED DIRECT TO [position]"),
    ("uM78LevelPosition", "LevelPosition", "AT [level] PROCEED DIRECT TO [position]"),
    ("uM79PositionRouteClearance", "PositionRouteClearanceIndex", "CLEARED TO [position] VIA [routeClearance]"),
    ("uM80RouteClearance", "RouteClearanceIndex", "CLEARED [routeClearance]"),
    ("uM81ProcedureName", "ProcedureName", "CLEARED [procedureName]"),
    ("uM82DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "CLEARED TO DEVIATE UP TO [specifiedDistance] [direction] OF ROUTE"),
    ("uM83PositionRouteClearance", "PositionRouteClearanceIndex", "AT [position] CLEARED [routeClearance]"),
    ("uM84PositionProcedureName", "PositionProcedureName", "AT [position] CLEARED [procedureName]"),
    ("uM85RouteClearance", "RouteClearanceIndex", "EXPECT [routeClearance]"),
    ("uM86PositionRouteClearance", "PositionRouteClearanceIndex", "AT [position] EXPECT [routeClearance]"),
    ("uM87Position", "Position", "EXPECT DIRECT TO [position]"),
    ("uM88PositionPosition", "PositionPosition", "AT [position] EXPECT DIRECT TO [position]"),
    ("uM89TimePosition", "TimePosition", "AT [time] EXPECT DIRECT TO [position]"),
    ("uM90LevelPosition", "LevelPosition", "AT [level] EXPECT DIRECT TO [position]"),
    ("uM91HoldClearance", "HoldClearance", "HOLD AT [position] MAINTAIN [level] INBOUND TRACK [degrees][direction] TURNS [legtype]"),
    ("uM92PositionLevel", "PositionLevel", "HOLD AT [position] AS PUBLISHED MAINTAIN [level]"),
    ("uM93Time", "Time", "EXPECT FURTHER CLEARANCE AT [time]"),
    ("uM94DirectionDegrees", "DirectionDegrees", "TURN [direction] HEADING [degrees]"),
    ("uM95DirectionDegrees", "DirectionDegrees", "TURN [direction] GROUND TRACK [degrees]"),
    ("uM96NULL", "NULL", "CONTINUE PRESENT HEADING"),
    ("uM97PositionDegrees", "PositionDegrees", "AT [position] FLY HEADING [degrees]"),
    ("uM98DirectionDegrees", "DirectionDegrees", "IMMEDIATELY TURN [direction] HEADING [degrees]"),
    ("uM99ProcedureName", "ProcedureName", "EXPECT [procedureName]"),
    ("uM100TimeSpeed", "TimeSpeed", "AT [time] EXPECT [speed]"),
    ("uM101PositionSpeed", "PositionSpeed", "AT [position] EXPECT [speed]"),
    ("uM102LevelSpeed", "LevelSpeed", "AT [level] EXPECT [speed]"),
    ("uM103TimeSpeedSpeed", "TimeSpeedSpeed", "AT [time] EXPECT [speed] TO [speed]"),
    ("uM104PositionSpeedSpeed", "PositionSpeedSpeed", "AT [position] EXPECT [speed] TO [speed]"),
    ("uM105LevelSpeedSpeed", "LevelSpeedSpeed", "AT [level] EXPECT [speed] TO [speed]"),
    ("uM106Speed", "Speed", "MAINTAIN [speed]"),
    ("uM107NULL", "NULL", "MAINTAIN PRESENT SPEED"),
    ("uM108Speed", "Speed", "MAINTAIN [speed] OR GREATER"),
    ("uM109Speed", "Speed", "MAINTAIN [speed] OR LESS"),
    ("uM110SpeedSpeed", "SpeedSpeed", "MAINTAIN [speed] TO [speed]"),
    ("uM111Speed", "Speed", "INCREASE SPEED TO [speed]"),
    ("uM112Speed", "Speed", "INCREASE SPEED TO [speed] OR GREATER"),
    ("uM113Speed", "Speed", "REDUCE SPEED TO [speed]"),
    ("uM114Speed", "Speed", "REDUCE SPEED TO [speed] OR LESS"),
    ("uM115Speed", "Speed", "DO NOT EXCEED [speed]"),
    ("uM116NULL", "NULL", "RESUME NORMAL SPEED"),
    ("uM117UnitNameFrequency", "UnitNameFrequency", "CONTACT [unitname] [frequency]"),
    ("uM118PositionUnitNameFrequency", "PositionUnitNameFrequency", "AT [position] CONTACT [unitname] [frequency]"),
    ("uM119TimeUnitNameFrequency", "TimeUnitNameFrequency", "AT [time] CONTACT [unitname] [frequency]"),
    ("uM120UnitNameFrequency", "UnitNameFrequency", "MONITOR [unitname] [frequency]"),
    ("uM121PositionUnitNameFrequency", "PositionUnitNameFrequency", "AT [position] MONITOR [unitname] [frequency]"),
    ("uM122TimeUnitNameFrequency", "TimeUnitNameFrequency", "AT [time] MONITOR [unitname] [frequency]"),
    ("uM123Code", "Code", "SQUAWK [code]"),
    ("uM124NULL", "NULL", "STOP SQUAWK"),
    ("uM125NULL", "NULL", "SQUAWK MODE CHARLIE"),
    ("uM126NULL", "NULL", "STOP SQUAWK MODE CHARLIE"),
    ("uM127NULL", "NULL", "REPORT BACK ON ROUTE"),
    ("uM128Level", "Level", "REPORT LEAVING [level]"),
    ("uM129Level", "Level", "REPORT MAINTAINING [level]"),
    ("uM130Position", "Position", "REPORT PASSING [position]"),
    ("uM131NULL", "NULL", "REPORT REMAINING FUEL AND PERSONS ON BOARD"),
    ("uM132NULL", "NULL", "REPORT POSITION"),
    ("uM133NULL", "NULL", "REPORT PRESENT LEVEL"),
    ("uM134SpeedTypeSpeedTypeSpeedType", "SpeedTypeSpeedTypeSpeedType", "REPORT [speedtype] [speedtype] [speedtype]SPEED"),
    ("uM135NULL", "NULL", "CONFIRM ASSIGNED LEVEL"),
    ("uM136NULL", "NULL", "CONFIRM ASSIGNED SPEED"),
    ("uM137NULL", "NULL", "CONFIRM ASSIGNED ROUTE"),
    ("uM138NULL", "NULL", "CONFIRM TIME OVER REPORTED WAYPOINT"),
    ("uM139NULL", "NULL", "CONFIRM REPORTED WAYPOINT"),
    ("uM140NULL", "NULL", "CONFIRM NEXT WAYPOINT"),
    ("uM141NULL", "NULL", "CONFIRM NEXT WAYPOINT ETA"),
    ("uM142NULL", "NULL", "CONFIRM ENSUING WAYPOINT"),
    ("uM143NULL", "NULL", "CONFIRM REQUEST"),
    ("uM144NULL", "NULL", "CONFIRM SQUAWK"),
    ("uM145NULL", "NULL", "REPORT HEADING"),
    ("uM146NULL", "NULL", "REPORT GROUND TRACK"),
    ("uM147NULL", "NULL", "REQUEST POSITION REPORT"),
    ("uM148Level", "Level", "WHEN CAN YOU ACCEPT [level]"),
    ("uM149LevelPosition", "LevelPosition", "CAN YOU ACCEPT [level] AT [position]"),
    ("uM150LevelTime", "LevelTime", "CAN YOU ACCEPT [level] AT [time]"),
    ("uM151Speed", "Speed", "WHEN CAN YOU ACCEPT [speed]"),
    ("uM152DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "WHEN CAN YOU ACCEPT [specifiedDistance] [direction] OFFSET"),
    ("uM153Altimeter", "Altimeter", "ALTIMETER [altimeter]"),
    ("uM154NULL", "NULL", "RADAR SERVICE TERMINATED"),
    ("uM155Position", "Position", "RADAR CONTACT [position]"),
    ("uM156NULL", "NULL", "RADAR CONTACT LOST"),
    ("uM157Frequency", "Frequency", "CHECK STUCK MICROPHONE [frequency]"),
    ("uM158AtisCode", "ATISCode", "ATIS [atiscode]"),
    ("uM159ErrorInformation", "ErrorInformation", "ERROR [errorInformation]"),
    ("uM160Facility", "Facility", "NEXT DATA AUTHORITY [facility]"),
    ("uM161NULL", "NULL", "END SERVICE"),
    ("uM162NULL", "NULL", "SERVICE UNAVAILABLE"),
    ("uM163FacilityDesignation", "FacilityDesignation", "[facilitydesignation]"),
    ("uM164NULL", "NULL", "WHEN READY"),
    ("uM165NULL", "NULL", "THEN"),
    ("uM166TrafficType", "TrafficType", "DUE TO [traffictype]TRAFFIC"),
    ("uM167NULL", "NULL", "DUE TO AIRSPACE RESTRICTION"),
    ("uM168NULL", "NULL", "DISREGARD"),
    ("uM169FreeText", "FreeText", "[freetext]"),
    ("uM170FreeText", "FreeText", "[freetext]"),
    ("uM171VerticalRate", "VerticalRate", "CLIMB AT [verticalRate] MINIMUM"),
    ("uM172VerticalRate", "VerticalRate", "CLIMB AT [verticalRate] MAXIMUM"),
    ("uM173VerticalRate", "VerticalRate", "DESCEND AT [verticalRate] MINIMUM"),
    ("uM174VerticalRate", "VerticalRate", "DESCEND AT [verticalRate] MAXIMUM"),
    ("uM175Level", "Level", "REPORT REACHING [level]"),
    ("uM176NULL", "NULL", "MAINTAIN OWN SEPARATION AND VMC"),
    ("uM177NULL", "NULL", "AT PILOTS DISCRETION"),
    ("uM178NULL", "NULL", "Reserved"),
    ("uM179NULL", "NULL", "SQUAWK IDENT"),
    ("uM180LevelLevel", "LevelLevel", "REPORT REACHING BLOCK [level] TO [level]"),
    ("uM181ToFromPosition", "ToFromPosition", "REPORT DISTANCE [tofrom] [position]"),
    ("uM182NULL", "NULL", "CONFIRM ATIS CODE"),
    ("uM183FreeText", "FreeText", "[freetext]"),
    ("uM184TimeToFromPosition", "TimeToFromPosition", "AT [time] REPORT DISTANCE [tofrom] [position]"),
    ("uM185PositionLevel", "PositionLevel", "AFTER PASSING [position] CLIMB TO [level]"),
    ("uM186PositionLevel", "PositionLevel", "AFTER PASSING [position] DESCEND TO [level]"),
    ("uM187FreeText", "FreeText", "[freetext]"),
    ("uM188PositionSpeed", "PositionSpeed", "AFTER PASSING [position] MAINTAIN [speed]"),
    ("uM189Speed", "Speed", "ADJUST SPEED TO [speed]"),
    ("uM190Degrees", "Degrees", "FLY HEADING [degrees]"),
    ("uM191NULL", "NULL", "ALL ATS TERMINATED"),
    ("uM192LevelTime", "LevelTime", "REACH [level] BY [time]"),
    ("uM193NULL", "NULL", "IDENTIFICATION LOST"),
    ("uM194FreeText", "FreeText", "[freetext]"),
    ("uM195FreeText", "FreeText", "[freetext]"),
    ("uM196FreeText", "FreeText", "[freetext]"),
    ("uM197FreeText", "FreeText", "[freetext]"),
    ("uM198FreeText", "FreeText", "[freetext]"),
    ("uM199FreeText", "FreeText", "[freetext]"),
    ("uM200NULL", "NULL", "REPORT REACHING"),
    ("uM201NULL", "NULL", "Not Used"),
    ("uM202NULL", "NULL", "Not Used"),
    ("uM203FreeText", "FreeText", "[freetext]"),
    ("uM204FreeText", "FreeText", "[freetext]"),
    ("uM205FreeText", "FreeText", "[freetext]"),
    ("uM206FreeText", "FreeText", "[freetext]"),
    ("uM207FreeText", "FreeText", "[freetext]"),
    ("uM208FreeText", "FreeText", "[freetext]"),
    ("uM209LevelPosition", "LevelPosition", "REACH [level] BY [position]"),
    ("uM210Position", "Position", "IDENTIFIED [position]"),
    ("uM211NULL", "NULL", "REQUEST FORWARDED"),
    ("uM212FacilityDesignationATISCode", "FacilityDesignationATISCode", "[facilitydesignation] ATIS [atiscode] CURRENT"),
    ("uM213FacilityDesignationAltimeter", "FacilityDesignationAltimeter", "[facilitydesignation] ALTIMETER [altimeter]"),
    ("uM214RunwayRVR", "RunwayRVR", "RVR RUNWAY [runway] [rvr]"),
    ("uM215DirectionDegrees", "DirectionDegrees", "TURN [direction][degrees]"),
    ("uM216NULL", "NULL", "REQUEST FLIGHT PLAN"),
    ("uM217NULL", "NULL", "REPORT ARRIVAL"),
    ("uM218NULL", "NULL", "REQUEST ALREADY RECEIVED"),
    ("uM219Level", "Level", "STOP CLIMB AT [level]"),
    ("uM220Level", "Level", "STOP DESCENT AT [level]"),
    ("uM221Degrees", "Degrees", "STOP TURN HEADING [degrees]"),
    ("uM222NULL", "NULL", "NO SPEED RESTRICTION"),
    ("uM223NULL", "NULL", "REDUCE TO MINIMUM APPROACH SPEED"),
    ("uM224NULL", "NULL", "NO DELAY EXPECTED"),
    ("uM225NULL", "NULL", "DELAY NOT DETERMINED"),
    ("uM226Time", "Time", "EXPECTED APPROACH TIME [time]"),
    ("uM227NULL", "NULL", "LOGICAL ACKNOWLEDGMENT"),
    ("uM228Position", "Position", "REPORT ETA [position]"),
    ("uM229NULL", "NULL", "REPORT ALTERNATE AERODROME"),
    ("uM230NULL", "NULL", "IMMEDIATELY"),
    ("uM231NULL", "NULL", "STATE PREFERRED LEVEL"),
    ("uM232NULL", "NULL", "STATE TOP OF DESCENT"),
    ("uM233NULL", "NULL", "USE OF LOGICAL ACKNOWLEDGMENT PROHIBITED"),
    ("uM234NULL", "NULL", "FLIGHT PLAN NOT HELD"),
    ("uM235NULL", "NULL", "ROGER 7500"),
    ("uM236NULL", "NULL", "LEAVE CONTROLLED AIRSPACE"),
    ("uM237NULL", "NULL", "REQUEST AGAIN WITH NEXT UNIT"),
];

/// (element name, argument ASN.1 type, phraseology) by CHOICE index
/// — generated from docs/asn1/atn-cpdlc.asn (ICAO Doc 9880 module).
pub const DOWNLINK_ELEMENTS: [(&str, &str, &str); 114] = [
    ("dM0NULL", "NULL", "WILCO"),
    ("dM1NULL", "NULL", "UNABLE"),
    ("dM2NULL", "NULL", "STANDBY"),
    ("dM3NULL", "NULL", "ROGER"),
    ("dM4NULL", "NULL", "AFFIRM"),
    ("dM5NULL", "NULL", "NEGATIVE"),
    ("dM6Level", "Level", "REQUEST [level]"),
    ("dM7LevelLevel", "LevelLevel", "REQUEST BLOCK [level] TO [level]"),
    ("dM8Level", "Level", "REQUEST CRUISE CLIMB TO [level]"),
    ("dM9Level", "Level", "REQUEST CLIMB TO [level]"),
    ("dM10Level", "Level", "REQUEST DESCENT TO [level]"),
    ("dM11PositionLevel", "PositionLevel", "AT [position] REQUEST CLIMB TO [level]"),
    ("dM12PositionLevel", "PositionLevel", "AT [position] REQUEST DESCENT TO [level]"),
    ("dM13TimeLevel", "TimeLevel", "AT [time] REQUEST CLIMB TO [level]"),
    ("dM14TimeLevel", "TimeLevel", "AT [time] REQUEST DESCENT TO [level]"),
    ("dM15DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "REQUEST OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("dM16PositionDistanceSpecifiedDirection", "PositionDistanceSpecifiedDirection", "AT [position] REQUEST OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("dM17TimeDistanceSpecifiedDirection", "TimeDistanceSpecifiedDirection", "AT [time] REQUEST OFFSET [specifiedDistance] [direction] OF ROUTE"),
    ("dM18Speed", "Speed", "REQUEST [speed]"),
    ("dM19SpeedSpeed", "SpeedSpeed", "REQUEST [speed] TO [speed]"),
    ("dM20NULL", "NULL", "REQUEST VOICE CONTACT"),
    ("dM21Frequency", "Frequency", "REQUEST VOICE CONTACT [frequency]"),
    ("dM22Position", "Position", "REQUEST DIRECT TO [position]"),
    ("dM23ProcedureName", "ProcedureName", "REQUEST [procedureName]"),
    ("dM24RouteClearance", "RouteClearanceIndex", "REQUEST CLEARANCE [routeClearance]"),
    ("dM25ClearanceType", "ClearanceType", "REQUEST [clearanceType] CLEARANCE"),
    ("dM26PositionRouteClearance", "PositionRouteClearanceIndex", "REQUEST WEATHER DEVIATION TO [position] VIA [routeClearance]"),
    ("dM27DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "REQUEST WEATHER DEVIATION UP TO [specifiedDistance] [direction] OF ROUTE"),
    ("dM28Level", "Level", "LEAVING [level]"),
    ("dM29Level", "Level", "CLIMBING TO [level]"),
    ("dM30Level", "Level", "DESCENDING TO [level]"),
    ("dM31Position", "Position", "PASSING [position]"),
    ("dM32Level", "Level", "PRESENT LEVEL [level]"),
    ("dM33Position", "Position", "PRESENT POSITION [position]"),
    ("dM34Speed", "Speed", "PRESENT SPEED [speed]"),
    ("dM35Degrees", "Degrees", "PRESENT HEADING [degrees]"),
    ("dM36Degrees", "Degrees", "PRESENT GROUND TRACK [degrees]"),
    ("dM37Level", "Level", "MAINTAINING [level]"),
    ("dM38Level", "Level", "ASSIGNED LEVEL [level]"),
    ("dM39Speed", "Speed", "ASSIGNED SPEED [speed]"),
    ("dM40RouteClearance", "RouteClearanceIndex", "ASSIGNED ROUTE [routeClearance]"),
    ("dM41NULL", "NULL", "BACK ON ROUTE"),
    ("dM42Position", "Position", "NEXT WAYPOINT [position]"),
    ("dM43Time", "Time", "NEXT WAYPOINT ETA [time]"),
    ("dM44Position", "Position", "ENSUING WAYPOINT [position]"),
    ("dM45Position", "Position", "REPORTED WAYPOINT [position]"),
    ("dM46Time", "Time", "REPORTED WAYPOINT [time]"),
    ("dM47Code", "Code", "SQUAWKING [code]"),
    ("dM48PositionReport", "PositionReport", "POSITION REPORT [positionreport]"),
    ("dM49Speed", "Speed", "WHEN CAN WE EXPECT [speed]"),
    ("dM50SpeedSpeed", "SpeedSpeed", "WHEN CAN WE EXPECT [speed] TO [speed]"),
    ("dM51NULL", "NULL", "WHEN CAN WE EXPECT BACK ON ROUTE"),
    ("dM52NULL", "NULL", "WHEN CAN WE EXPECT LOWER LEVEL"),
    ("dM53NULL", "NULL", "WHEN CAN WE EXPECT HIGHER LEVEL Urg(L)/Alr(L)/Resp(Y)"),
    ("dM54Level", "Level", "WHEN CAN WE EXPECT CRUISE CLIMB TO [level]"),
    ("dM55NULL", "NULL", "PAN PAN PAN"),
    ("dM56NULL", "NULL", "MAYDAY MAYDAY MAYDAY"),
    ("dM57RemainingFuelPersonsOnBoard", "RemainingFuelPersonsOnBoard", "[remainingFuel] OF FUEL REMAINING AND [personsonboard] PERSONS ON BOARD"),
    ("dM58NULL", "NULL", "CANCEL EMERGENCY"),
    ("dM59PositionRouteClearance", "PositionRouteClearanceIndex", "DIVERTING TO [position] VIA [routeClearance]"),
    ("dM60DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "OFFSETTING [specifiedDistance] [direction] OF ROUTE"),
    ("dM61Level", "Level", "DESCENDING TO [level]"),
    ("dM62ErrorInformation", "ErrorInformation", "ERROR [errorInformation]"),
    ("dM63NULL", "NULL", "NOT CURRENT DATA AUTHORITY"),
    ("dM64FacilityDesignation", "FacilityDesignation", "[facilitydesignation]"),
    ("dM65NULL", "NULL", "DUE TO WEATHER"),
    ("dM66NULL", "NULL", "DUE TO AIRCRAFT PERFORMANCE"),
    ("dM67FreeText", "FreeText", "[freetext]"),
    ("dM68FreeText", "FreeText", "[freetext]"),
    ("dM69NULL", "NULL", "REQUEST VMC DESCENT"),
    ("dM70Degrees", "Degrees", "REQUEST HEADING [degrees]"),
    ("dM71Degrees", "Degrees", "REQUEST GROUND TRACK [degrees]"),
    ("dM72Level", "Level", "REACHING [level]"),
    ("dM73Versionnumber", "VersionNumber", "[versionnumber]"),
    ("dM74NULL", "NULL", "REQUEST TO MAINTAIN OWN SEPARATION AND VMC"),
    ("dM75NULL", "NULL", "AT PILOTS DISCRETION"),
    ("dM76LevelLevel", "LevelLevel", "REACHING BLOCK [level] TO [level]"),
    ("dM77LevelLevel", "LevelLevel", "ASSIGNED BLOCK [level] TO [level]"),
    ("dM78TimeDistanceToFromPosition", "TimeDistanceToFromPosition", "AT [time] [distance] [tofrom] [position]"),
    ("dM79AtisCode", "ATISCode", "ATIS [atiscode]"),
    ("dM80DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "DEVIATING UP TO [specifiedDistance] [direction] OF ROUTE"),
    ("dM81LevelTime", "LevelTime", "WE CAN ACCEPT [level] AT [time]"),
    ("dM82Level", "Level", "WE CANNOT ACCEPT [level]"),
    ("dM83SpeedTime", "SpeedTime", "WE CAN ACCEPT [speed] AT [time]"),
    ("dM84Speed", "Speed", "WE CANNOT ACCEPT [speed]"),
    ("dM85DistanceSpecifiedDirectionTime", "DistanceSpecifiedDirectionTime", "WE CAN ACCEPT [specifiedDistance] [direction] AT [time]"),
    ("dM86DistanceSpecifiedDirection", "DistanceSpecifiedDirection", "WE CANNOT ACCEPT [specifiedDistance] [direction]"),
    ("dM87Level", "Level", "WHEN CAN WE EXPECT CLIMB TO [level]"),
    ("dM88Level", "Level", "WHEN CAN WE EXPECT DESCENT TO [level]"),
    ("dM89UnitnameFrequency", "UnitNameFrequency", "MONITORING [unitname] [frequency]"),
    ("dM90FreeText", "FreeText", "[freetext]"),
    ("dM91FreeText", "FreeText", "[freetext]"),
    ("dM92FreeText", "FreeText", "[freetext]"),
    ("dM93FreeText", "FreeText", "[freetext]"),
    ("dM94FreeText", "FreeText", "[freetext]"),
    ("dM95FreeText", "FreeText", "[freetext]"),
    ("dM96FreeText", "FreeText", "[freetext]"),
    ("dM97FreeText", "FreeText", "[freetext]"),
    ("dM98FreeText", "FreeText", "[freetext]"),
    ("dM99NULL", "NULL", "CURRENT DATA AUTHORITY"),
    ("dM100NULL", "NULL", "LOGICAL ACKNOWLEDGMENT"),
    ("dM101NULL", "NULL", "REQUEST END OF SERVICE"),
    ("dM102NULL", "NULL", "LANDING REPORT"),
    ("dM103NULL", "NULL", "CANCELLING IFR"),
    ("dM104PositionTime", "PositionTime", "ETA[position][time]"),
    ("dM105Airport", "Airport", "ALTERNATE AERODROME[airport]"),
    ("dM106Level", "Level", "PREFERRED LEVEL[level]"),
    ("dM107NULL", "NULL", "NOT AUTHORIZED NEXT DATA AUTHORITY"),
    ("dM108NULL", "NULL", "DE-ICING COMPLETE"),
    ("dM109Time", "Time", "TOP OF DESCENT [time]"),
    ("dM110Position", "Position", "TOP OF DESCENT [position]"),
    ("dM111TimePosition", "TimePosition", "TOP OF DESCENT [time] [position]"),
    ("dM112NULL", "NULL", "SQUAWKING 7500"),
    ("dM113SpeedTypeSpeedTypeSpeedTypeSpeed", "SpeedTypeSpeedTypeSpeedTypeSpeed", "[speedType] [speedType] [speedType] SPEED [speed]"),
];

