//! Generated from libacars (MIT): FANSATC*MsgElementId enums (CHOICE
//! order = UPER index) joined with asn1-format-cpdlc-text.c labels.

pub(crate) const DOWNLINK_ELEMENTS: [(&str, &str); 129] = [
    ("dM0NULL", "WILCO"),
    ("dM1NULL", "UNABLE"),
    ("dM2NULL", "STANDBY"),
    ("dM3NULL", "ROGER"),
    ("dM4NULL", "AFFIRM"),
    ("dM5NULL", "NEGATIVE"),
    ("dM6Altitude", "REQUEST [altitude]"),
    ("dM7AltitudeAltitude", "REQUEST BLOCK [altitude] TO [altitude]"),
    ("dM8Altitude", "REQUEST CRUISE CLIMB TO [altitude]"),
    ("dM9Altitude", "REQUEST CLIMB TO [altitude]"),
    ("dM10Altitude", "REQUEST DESCENT TO [altitude]"),
    ("dM11PositionAltitude", "AT [position] REQUEST CLIMB TO [altitude]"),
    ("dM12PositionAltitude", "AT [position] REQUEST DESCENT TO [altitude]"),
    ("dM13TimeAltitude", "AT [time] REQUEST CLIMB TO [altitude]"),
    ("dM14TimeAltitude", "AT [time] REQUEST DESCENT TO [altitude]"),
    ("dM15DistanceOffsetDirection", "REQUEST OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("dM16PositionDistanceOffsetDirection", "AT [position] REQUEST OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("dM17TimeDistanceOffsetDirection", "AT [time] REQUEST OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("dM18Speed", "REQUEST [speed]"),
    ("dM19SpeedSpeed", "REQUEST [speed] TO [speed]"),
    ("dM20NULL", "REQUEST VOICE CONTACT"),
    ("dM21Frequency", "REQUEST VOICE CONTACT [frequency]"),
    ("dM22Position", "REQUEST DIRECT TO [position]"),
    ("dM23ProcedureName", "REQUEST [procedurename]"),
    ("dM24RouteClearance", "REQUEST [routeclearance]"),
    ("dM25NULL", "REQUEST CLEARANCE"),
    ("dM26PositionRouteClearance", "REQUEST WEATHER DEVIATION TO [position] VIA [routeclearance]"),
    ("dM27DistanceOffsetDirection", "REQUEST WEATHER DEVIATION UP TO [distanceoffset] [direction] OF ROUTE"),
    ("dM28Altitude", "LEAVING [altitude]"),
    ("dM29Altitude", "CLIMBING TO [altitude]"),
    ("dM30Altitude", "DESCENDING TO [altitude]"),
    ("dM31Position", "PASSING [position]"),
    ("dM32Altitude", "PRESENT ALTITUDE [altitude]"),
    ("dM33Position", "PRESENT POSITION [position]"),
    ("dM34Speed", "PRESENT SPEED [speed]"),
    ("dM35Degrees", "PRESENT HEADING [degrees]"),
    ("dM36Degrees", "PRESENT GROUND TRACK [degrees]"),
    ("dM37Altitude", "LEVEL [altitude]"),
    ("dM38Altitude", "ASSIGNED ALTITUDE [altitude]"),
    ("dM39Speed", "ASSIGNED SPEED [speed]"),
    ("dM40RouteClearance", "ASSIGNED ROUTE [routeclearance]"),
    ("dM41NULL", "BACK ON ROUTE"),
    ("dM42Position", "NEXT WAYPOINT [position]"),
    ("dM43Time", "NEXT WAYPOINT ETA [time]"),
    ("dM44Position", "ENSUING WAYPOINT [position]"),
    ("dM45Position", "REPORTED WAYPOINT [position]"),
    ("dM46Time", "REPORTED WAYPOINT [time]"),
    ("dM47BeaconCode", "SQUAWKING [beaconcode]"),
    ("dM48PositionReport", "POSITION REPORT [positionreport]"),
    ("dM49Speed", "WHEN CAN WE EXPECT [speed]"),
    ("dM50SpeedSpeed", "WHEN CAN WE EXPECT [speed] TO [speed]"),
    ("dM51NULL", "WHEN CAN WE EXPECT BACK ON ROUTE"),
    ("dM52NULL", "WHEN CAN WE EXPECT LOWER ALTITUDE"),
    ("dM53NULL", "WHEN CAN WE EXPECT HIGHER ALTITUDE"),
    ("dM54Altitude", "WHEN CAN WE EXPECT CRUISE CLIMB TO [altitude]"),
    ("dM55NULL", "PAN PAN PAN"),
    ("dM56NULL", "MAYDAY MAYDAY MAYDAY"),
    ("dM57RemainingFuelRemainingSouls", "[remainingfuel] OF FUEL REMAINING AND [remainingsouls] SOULS ON BOARD"),
    ("dM58NULL", "CANCEL EMERGENCY"),
    ("dM59PositionRouteClearance", "DIVERTING TO [position] VIA [routeclearance]"),
    ("dM60DistanceOffsetDirection", "OFFSETTING [distanceoffset] [direction] OF ROUTE"),
    ("dM61Altitude", "DESCENDING TO [altitude]"),
    ("dM62ErrorInformation", "ERROR [errorinformation]"),
    ("dM63NULL", "NOT CURRENT DATA AUTHORITY"),
    ("dM64ICAOfacilitydesignation", "[icaofacilitydesignation]"),
    ("dM65NULL", "DUE TO WEATHER"),
    ("dM66NULL", "DUE TO AIRCRAFT PERFORMANCE"),
    ("dM67FreeText", "[freetext]"),
    ("dM68FreeText", "[freetext]"),
    ("dM69NULL", "REQUEST VMC DESCENT"),
    ("dM70Degrees", "REQUEST HEADING [degrees]"),
    ("dM71Degrees", "REQUEST GROUND TRACK [degrees]"),
    ("dM72Altitude", "REACHING [altitude]"),
    ("dM73VersionNumber", "[versionnumber]"),
    ("dM74NULL", "MAINTAIN OWN SEPARATION AND VMC"),
    ("dM75NULL", "AT PILOTS DISCRETION"),
    ("dM76AltitudeAltitude", "REACHING BLOCK [altitude] TO [altitude]"),
    ("dM77AltitudeAltitude", "ASSIGNED BLOCK [altitude] TO [altitude]"),
    ("dM78TimeDistanceToFromPosition", "AT [time] [distance] [tofrom] [position]"),
    ("dM79ATISCode", "ATIS [atiscode]"),
    ("dM80DistanceOffsetDirection", "DEVIATING [distanceoffset][direction] OF ROUTE"),
    ("dM81NULL", "(reserved: dM81NULL)"),
    ("dM82NULL", "(reserved: dM82NULL)"),
    ("dM83NULL", "(reserved: dM83NULL)"),
    ("dM84NULL", "(reserved: dM84NULL)"),
    ("dM85NULL", "(reserved: dM85NULL)"),
    ("dM86NULL", "(reserved: dM86NULL)"),
    ("dM87NULL", "(reserved: dM87NULL)"),
    ("dM88NULL", "(reserved: dM88NULL)"),
    ("dM89NULL", "(reserved: dM89NULL)"),
    ("dM90NULL", "(reserved: dM90NULL)"),
    ("dM91NULL", "(reserved: dM91NULL)"),
    ("dM92NULL", "(reserved: dM92NULL)"),
    ("dM93NULL", "(reserved: dM93NULL)"),
    ("dM94NULL", "(reserved: dM94NULL)"),
    ("dM95NULL", "(reserved: dM95NULL)"),
    ("dM96NULL", "(reserved: dM96NULL)"),
    ("dM97NULL", "(reserved: dM97NULL)"),
    ("dM98NULL", "(reserved: dM98NULL)"),
    ("dM99NULL", "(reserved: dM99NULL)"),
    ("dM100NULL", "(reserved: dM100NULL)"),
    ("dM101NULL", "(reserved: dM101NULL)"),
    ("dM102NULL", "(reserved: dM102NULL)"),
    ("dM103NULL", "(reserved: dM103NULL)"),
    ("dM104NULL", "(reserved: dM104NULL)"),
    ("dM105NULL", "(reserved: dM105NULL)"),
    ("dM106NULL", "(reserved: dM106NULL)"),
    ("dM107NULL", "(reserved: dM107NULL)"),
    ("dM108NULL", "(reserved: dM108NULL)"),
    ("dM109NULL", "(reserved: dM109NULL)"),
    ("dM110NULL", "(reserved: dM110NULL)"),
    ("dM111NULL", "(reserved: dM111NULL)"),
    ("dM112NULL", "(reserved: dM112NULL)"),
    ("dM113NULL", "(reserved: dM113NULL)"),
    ("dM114NULL", "(reserved: dM114NULL)"),
    ("dM115NULL", "(reserved: dM115NULL)"),
    ("dM116NULL", "(reserved: dM116NULL)"),
    ("dM117NULL", "(reserved: dM117NULL)"),
    ("dM118NULL", "(reserved: dM118NULL)"),
    ("dM119NULL", "(reserved: dM119NULL)"),
    ("dM120NULL", "(reserved: dM120NULL)"),
    ("dM121NULL", "(reserved: dM121NULL)"),
    ("dM122NULL", "(reserved: dM122NULL)"),
    ("dM123NULL", "(reserved: dM123NULL)"),
    ("dM124NULL", "(reserved: dM124NULL)"),
    ("dM125NULL", "(reserved: dM125NULL)"),
    ("dM126NULL", "(reserved: dM126NULL)"),
    ("dM127NULL", "(reserved: dM127NULL)"),
    ("dM128NULL", "(reserved: dM128NULL)"),
];

pub(crate) const UPLINK_ELEMENTS: [(&str, &str); 183] = [
    ("uM0NULL", "UNABLE"),
    ("uM1NULL", "STANDBY"),
    ("uM2NULL", "REQUEST DEFERRED"),
    ("uM3NULL", "ROGER"),
    ("uM4NULL", "AFFIRM"),
    ("uM5NULL", "NEGATIVE"),
    ("uM6Altitude", "EXPECT [altitude]"),
    ("uM7Time", "EXPECT CLIMB AT [time]"),
    ("uM8Position", "EXPECT CLIMB AT [position]"),
    ("uM9Time", "EXPECT DESCENT AT [time]"),
    ("uM10Position", "EXPECT DESCENT AT [position]"),
    ("uM11Time", "EXPECT CRUISE CLIMB AT [time]"),
    ("uM12Position", "EXPECT CRUISE CLIMB AT [position]"),
    ("uM13TimeAltitude", "AT [time] EXPECT CLIMB TO [altitude]"),
    ("uM14PositionAltitude", "AT [position] EXPECT CLIMB TO [altitude]"),
    ("uM15TimeAltitude", "AT [time] EXPECT DESCENT TO [altitude]"),
    ("uM16PositionAltitude", "AT [position] EXPECT DESCENT TO [altitude]"),
    ("uM17TimeAltitude", "AT [time] EXPECT CRUISE CLIMB TO [altitude]"),
    ("uM18PositionAltitude", "AT [position] EXPECT CRUISE CLIMB TO [altitude]"),
    ("uM19Altitude", "MAINTAIN [altitude]"),
    ("uM20Altitude", "CLIMB TO AND MAINTAIN [altitude]"),
    ("uM21TimeAltitude", "AT [time] CLIMB TO AND MAINTAIN [altitude]"),
    ("uM22PositionAltitude", "AT [position] CLIMB TO AND MAINTAIN [altitude]"),
    ("uM23Altitude", "DESCEND TO AND MAINTAIN [altitude]"),
    ("uM24TimeAltitude", "AT [time] DESCEND TO AND MAINTAIN [altitude]"),
    ("uM25PositionAltitude", "AT [position] DESCEND TO AND MAINTAIN [altitude]"),
    ("uM26AltitudeTime", "CLIMB TO REACH [altitude] BY [time]"),
    ("uM27AltitudePosition", "CLIMB TO REACH [altitude] BY [position]"),
    ("uM28AltitudeTime", "DESCEND TO REACH [altitude] BY [time]"),
    ("uM29AltitudePosition", "DESCEND TO REACH [altitude] BY [position]"),
    ("uM30AltitudeAltitude", "MAINTAIN BLOCK [altitude] TO [altitude]"),
    ("uM31AltitudeAltitude", "CLIMB TO AND MAINTAIN BLOCK [altitude] TO [altitude]"),
    ("uM32AltitudeAltitude", "DESCEND TO AND MAINTAIN BLOCK [altitude] TO [altitude]"),
    ("uM33Altitude", "CRUISE [altitude]"),
    ("uM34Altitude", "CRUISE CLIMB TO [altitude]"),
    ("uM35Altitude", "CRUISE CLIMB ABOVE [altitude]"),
    ("uM36Altitude", "EXPEDITE CLIMB TO [altitude]"),
    ("uM37Altitude", "EXPEDITE DESCENT TO [altitude]"),
    ("uM38Altitude", "IMMEDIATELY CLIMB TO [altitude]"),
    ("uM39Altitude", "IMMEDIATELY DESCEND TO [altitude]"),
    ("uM40Altitude", "IMMEDIATELY STOP CLIMB AT [altitude]"),
    ("uM41Altitude", "IMMEDIATELY STOP DESCENT AT [altitude]"),
    ("uM42PositionAltitude", "EXPECT TO CROSS [position] AT [altitude]"),
    ("uM43PositionAltitude", "EXPECT TO CROSS [position] AT OR ABOVE [altitude]"),
    ("uM44PositionAltitude", "EXPECT TO CROSS [position] AT OR BELOW [altitude]"),
    ("uM45PositionAltitude", "EXPECT TO CROSS [position] AT AND MAINTAIN [altitude]"),
    ("uM46PositionAltitude", "CROSS [position] AT [altitude]"),
    ("uM47PositionAltitude", "CROSS [position] AT OR ABOVE [altitude]"),
    ("uM48PositionAltitude", "CROSS [position] AT OR BELOW [altitude]"),
    ("uM49PositionAltitude", "CROSS [position] AT AND MAINTAIN [altitude]"),
    ("uM50PositionAltitudeAltitude", "CROSS [position] BETWEEN [altitude] AND [altitude]"),
    ("uM51PositionTime", "CROSS [position] AT [time]"),
    ("uM52PositionTime", "CROSS [position] AT OR BEFORE [time]"),
    ("uM53PositionTime", "CROSS [position] AT OR AFTER [time]"),
    ("uM54PositionTimeTime", "CROSS [position] BETWEEN [time] AND [time]"),
    ("uM55PositionSpeed", "CROSS [position] AT [speed]"),
    ("uM56PositionSpeed", "CROSS [position] AT OR LESS THAN [speed]"),
    ("uM57PositionSpeed", "CROSS [position] AT OR GREATER THAN [speed]"),
    ("uM58PositionTimeAltitude", "CROSS [position] AT [time] AT [altitude]"),
    ("uM59PositionTimeAltitude", "CROSS [position] AT OR BEFORE [time] AT [altitude]"),
    ("uM60PositionTimeAltitude", "CROSS [position] AT OR AFTER [time] AT [altitude]"),
    ("uM61PositionAltitudeSpeed", "CROSS [position] AT AND MAINTAIN [altitude] AT [speed]"),
    ("uM62TimePositionAltitude", "AT [time] CROSS [position] AT AND MAINTAIN [altitude]"),
    ("uM63TimePositionAltitudeSpeed", "AT [time] CROSS [position] AT AND MAINTAIN [altitude] AT [speed]"),
    ("uM64DistanceOffsetDirection", "OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("uM65PositionDistanceOffsetDirection", "AT [position] OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("uM66TimeDistanceOffsetDirection", "AT [time] OFFSET [distanceoffset] [direction] OF ROUTE"),
    ("uM67NULL", "PROCEED BACK ON ROUTE"),
    ("uM68Position", "REJOIN ROUTE BY [position]"),
    ("uM69Time", "REJOIN ROUTE BY [time]"),
    ("uM70Position", "EXPECT BACK ON ROUTE BY [position]"),
    ("uM71Time", "EXPECT BACK ON ROUTE BY [time]"),
    ("uM72NULL", "RESUME OWN NAVIGATION"),
    ("uM73Predepartureclearance", "[predepartureclearance]"),
    ("uM74Position", "PROCEED DIRECT TO [position]"),
    ("uM75Position", "WHEN ABLE PROCEED DIRECT TO [position]"),
    ("uM76TimePosition", "AT [time] PROCEED DIRECT TO [position]"),
    ("uM77PositionPosition", "AT [position] PROCEED DIRECT TO [position]"),
    ("uM78AltitudePosition", "AT [altitude] PROCEED DIRECT TO [position]"),
    ("uM79PositionRouteClearance", "CLEARED TO [position] VIA [routeclearance]"),
    ("uM80RouteClearance", "CLEARED [routeclearance]"),
    ("uM81ProcedureName", "CLEARED [procedurename]"),
    ("uM82DistanceOffsetDirection", "CLEARED TO DEVIATE UP TO [distanceoffset] [direction] OF ROUTE"),
    ("uM83PositionRouteClearance", "AT [position] CLEARED [routeclearance]"),
    ("uM84PositionProcedureName", "AT [position] CLEARED [procedurename]"),
    ("uM85RouteClearance", "EXPECT [routeclearance]"),
    ("uM86PositionRouteClearance", "AT [position] EXPECT [routeclearance]"),
    ("uM87Position", "EXPECT DIRECT TO [position]"),
    ("uM88PositionPosition", "AT [position] EXPECT DIRECT TO [position]"),
    ("uM89TimePosition", "AT [time] EXPECT DIRECT TO [position]"),
    ("uM90AltitudePosition", "AT [altitude] EXPECT DIRECT TO [position]"),
    ("uM91HoldClearance", "HOLD AT [position] MAINTAIN [altitude] INBOUND TRACK [degrees] [direction] TURNS [legtype]"),
    ("uM92PositionAltitude", "HOLD AT [position] AS PUBLISHED MAINTAIN [altitude]"),
    ("uM93Time", "EXPECT FURTHER CLEARANCE AT [time]"),
    ("uM94DirectionDegrees", "TURN [direction] HEADING [degrees]"),
    ("uM95DirectionDegrees", "TURN [direction] GROUND TRACK [degrees]"),
    ("uM96NULL", "FLY PRESENT HEADING"),
    ("uM97PositionDegrees", "AT [position] FLY HEADING [degrees]"),
    ("uM98DirectionDegrees", "IMMEDIATELY TURN [direction] HEADING [degrees]"),
    ("uM99ProcedureName", "EXPECT [procedurename]"),
    ("uM100TimeSpeed", "AT [time] EXPECT [speed]"),
    ("uM101PositionSpeed", "AT [position] EXPECT [speed]"),
    ("uM102AltitudeSpeed", "AT [altitude] EXPECT [speed]"),
    ("uM103TimeSpeedSpeed", "AT [time] EXPECT [speed] TO [speed]"),
    ("uM104PositionSpeedSpeed", "AT [position] EXPECT [speed] TO [speed]"),
    ("uM105AltitudeSpeedSpeed", "AT [altitude] EXPECT [speed] TO [speed]"),
    ("uM106Speed", "MAINTAIN [speed]"),
    ("uM107NULL", "MAINTAIN PRESENT SPEED"),
    ("uM108Speed", "MAINTAIN [speed] OR GREATER"),
    ("uM109Speed", "MAINTAIN [speed] OR LESS"),
    ("uM110SpeedSpeed", "MAINTAIN [speed] TO [speed]"),
    ("uM111Speed", "INCREASE SPEED TO [speed]"),
    ("uM112Speed", "INCREASE SPEED TO [speed] OR GREATER"),
    ("uM113Speed", "REDUCE SPEED TO [speed]"),
    ("uM114Speed", "REDUCE SPEED TO [speed] OR LESS"),
    ("uM115Speed", "DO NOT EXCEED [speed]"),
    ("uM116NULL", "RESUME NORMAL SPEED"),
    ("uM117ICAOunitnameFrequency", "CONTACT [icaounitname] [frequency]"),
    ("uM118PositionICAOunitnameFrequency", "AT [position] CONTACT [icaounitname] [frequency]"),
    ("uM119TimeICAOunitnameFrequency", "AT [time] CONTACT [icaounitname] [frequency]"),
    ("uM120ICAOunitnameFrequency", "MONITOR [icaounitname] [frequency]"),
    ("uM121PositionICAOunitnameFrequency", "AT [position] MONITOR [icaounitname] [frequency]"),
    ("uM122TimeICAOunitnameFrequency", "AT [time] MONITOR [icaounitname] [frequency]"),
    ("uM123BeaconCode", "SQUAWK [beaconcode]"),
    ("uM124NULL", "STOP SQUAWK"),
    ("uM125NULL", "SQUAWK ALTITUDE"),
    ("uM126NULL", "STOP ALTITUDE SQUAWK"),
    ("uM127NULL", "REPORT BACK ON ROUTE"),
    ("uM128Altitude", "REPORT LEAVING [altitude]"),
    ("uM129Altitude", "REPORT LEVEL [altitude]"),
    ("uM130Position", "REPORT PASSING [position]"),
    ("uM131NULL", "REPORT REMAINING FUEL AND SOULS ON BOARD"),
    ("uM132NULL", "CONFIRM POSITION"),
    ("uM133NULL", "CONFIRM ALTITUDE"),
    ("uM134NULL", "CONFIRM SPEED"),
    ("uM135NULL", "CONFIRM ASSIGNED ALTITUDE"),
    ("uM136NULL", "CONFIRM ASSIGNED SPEED"),
    ("uM137NULL", "CONFIRM ASSIGNED ROUTE"),
    ("uM138NULL", "CONFIRM TIME OVER REPORTED WAYPOINT"),
    ("uM139NULL", "CONFIRM REPORTED WAYPOINT"),
    ("uM140NULL", "CONFIRM NEXT WAYPOINT"),
    ("uM141NULL", "CONFIRM NEXT WAYPOINT ETA"),
    ("uM142NULL", "CONFIRM ENSUING WAYPOINT"),
    ("uM143NULL", "CONFIRM REQUEST"),
    ("uM144NULL", "CONFIRM SQUAWK"),
    ("uM145NULL", "CONFIRM HEADING"),
    ("uM146NULL", "CONFIRM GROUND TRACK"),
    ("uM147NULL", "REQUEST POSITION REPORT"),
    ("uM148Altitude", "WHEN CAN YOU ACCEPT [altitude]"),
    ("uM149AltitudePosition", "CAN YOU ACCEPT [altitude] AT [position]"),
    ("uM150AltitudeTime", "CAN YOU ACCEPT [altitude] AT [time]"),
    ("uM151Speed", "WHEN CAN YOU ACCEPT [speed]"),
    ("uM152DistanceOffsetDirection", "WHEN CAN YOU ACCEPT [distanceoffset] [direction] OFFSET"),
    ("uM153Altimeter", "ALTIMETER [altimeter]"),
    ("uM154NULL", "RADAR SERVICES TERMINATED"),
    ("uM155Position", "RADAR CONTACT [position]"),
    ("uM156NULL", "RADAR CONTACT LOST"),
    ("uM157Frequency", "CHECK STUCK MICROPHONE [frequency]"),
    ("uM158ATISCode", "ATIS [atiscode]"),
    ("uM159ErrorInformation", "ERROR [errorinformation]"),
    ("uM160ICAOfacilitydesignation", "NEXT DATA AUTHORITY [icaofacilitydesignation]"),
    ("uM161NULL", "END SERVICE"),
    ("uM162NULL", "SERVICE UNAVAILABLE"),
    ("uM163ICAOfacilitydesignationTp4table", "[icaofacilitydesignation] [tp4table]"),
    ("uM164NULL", "WHEN READY"),
    ("uM165NULL", "THEN"),
    ("uM166NULL", "DUE TO TRAFFIC"),
    ("uM167NULL", "DUE TO AIRSPACE RESTRICTION"),
    ("uM168NULL", "DISREGARD"),
    ("uM169FreeText", "[freetext]"),
    ("uM170FreeText", "[freetext]"),
    ("uM171VerticalRate", "CLIMB AT [verticalrate] MINIMUM"),
    ("uM172VerticalRate", "CLIMB AT [verticalrate] MAXIMUM"),
    ("uM173VerticalRate", "DESCEND AT [verticalrate] MINIMUM"),
    ("uM174VerticalRate", "DESCEND AT [verticalrate] MAXIMUM"),
    ("uM175Altitude", "REPORT REACHING [altitude]"),
    ("uM176NULL", "MAINTAIN OWN SEPARATION AND VMC"),
    ("uM177NULL", "AT PILOTS DISCRETION"),
    ("uM178NULL", "[trackdetailmsg-deleted]"),
    ("uM179NULL", "SQUAWK IDENT"),
    ("uM180AltitudeAltitude", "REPORT REACHING BLOCK [altitude] TO [altitude]"),
    ("uM181ToFromPosition", "REPORT DISTANCE [tofrom] [position]"),
    ("uM182NULL", "CONFIRM ATIS CODE"),
];
