//! BCH(31,21,2) cyclic block code used by every POCSAG codeword.
//!
//! # Spec provenance
//!
//! POCSAG = CCIR Radiopaging Code No.1, standardised as **ITU-R
//! Recommendation M.584-2, "Codes and formats for radio paging"**, Annex 1
//! ("The radiopaging code No.1", §2 "Code structure"). Each 32-bit codeword
//! is:
//!
//! ```text
//!   bit 1 (MSB)        : flag  (0 = address codeword, 1 = message codeword)
//!   bits 2..=21        : 20 message bits  (address codeword: 18 addr + 2 fn)
//!   bits 22..=31       : 10 BCH parity check bits  (BCH(31,21))
//!   bit 32 (LSB)       : 1 even-parity bit over bits 1..=31
//! ```
//!
//! The first 31 bits form a **BCH(31,21)** code generated by the primitive
//! polynomial
//!
//! ```text
//!   g(x) = x^10 + x^9 + x^8 + x^6 + x^5 + x^3 + 1
//! ```
//!
//! (ITU-R M.584-2, Annex 1 §2.2 "Check bits"; the same polynomial is quoted in
//! the CCIR Radiopaging Code No.1 definition and reproduced by every public
//! POCSAG reference, e.g. the multimon-ng `pocsag.c` `BCH_POLY`). As a bit
//! pattern of its 11 coefficients (x^10 … x^0) that is
//! `1 1 1 0 1 1 0 1 0 0 1` = **0x769**.
//!
//! BCH(31,21,2) corrects up to **2** bit errors over the 31 protected bits.
//! This module implements:
//!   - [`parity_remainder`] — the BCH syndrome (remainder of the 31-bit word
//!     divided by `g(x)`); zero ⇔ a valid codeword.
//!   - [`encode`] — append the 10 check bits + even-parity bit to 21 data bits.
//!   - [`correct`] — syndrome decoding that flips 0, 1 or 2 bits to reach a
//!     valid codeword, returning the number of bits corrected (or `None` if no
//!     correction within the BCH distance succeeds).

/// BCH(31,21) generator polynomial coefficients x^10..x^0 = 0x769.
/// (ITU-R M.584-2, Annex 1 §2.2.)
pub const BCH_POLY: u32 = 0x769;

/// The 32-bit idle codeword, ITU-R M.584-2 Annex 1 §2.3: `0x7A89C197`.
/// Transmitted in unused codeword positions of a batch.
pub const IDLE_CODEWORD: u32 = 0x7A89_C197;

/// Frame-synchronisation codeword, ITU-R M.584-2 Annex 1 §2.4: `0x7CD215D8`.
/// Precedes every batch of 8 frames.
pub const SYNC_CODEWORD: u32 = 0x7CD2_15D8;

/// Compute the BCH syndrome: remainder of the top 31 bits of `cw` (bits
/// 31..=1, i.e. excluding the even-parity LSB) modulo `g(x)`.
///
/// The 21 data bits sit in positions 31..=11 and the 10 check bits in 10..=1;
/// dividing the whole 31-bit word by `g(x)` yields 0 for a valid codeword and
/// the error syndrome otherwise.
pub fn parity_remainder(cw: u32) -> u32 {
    // Work on the 31 protected bits (drop the parity LSB).
    let mut acc = cw >> 1;
    // Long division MSB-first: align g(x) (degree 10) under each set bit from
    // position 30 down to 10.
    for bit in (10..31).rev() {
        if acc & (1 << bit) != 0 {
            acc ^= BCH_POLY << (bit - 10);
        }
    }
    acc // < 2^10: the 10-bit remainder (syndrome)
}

/// Even parity over the top 31 bits (bits 31..=1). POCSAG uses *even* parity:
/// the parity bit is chosen so the total number of 1s across all 32 bits is
/// even.
pub fn parity_bit(cw_31: u32) -> u32 {
    cw_31.count_ones() & 1
}

/// True iff `cw` is a structurally valid POCSAG codeword: BCH syndrome zero
/// and overall even parity.
pub fn is_valid(cw: u32) -> bool {
    parity_remainder(cw) == 0 && (cw.count_ones() & 1) == 0
}

/// Encode 21 data bits (`data` in the low 21 bits, MSB = flag) into a full
/// 32-bit POCSAG codeword: BCH(31,21) check bits + even parity.
pub fn encode(data21: u32) -> u32 {
    let data21 = data21 & 0x1F_FFFF; // 21 bits
                                     // Message part occupies bits 31..=11; compute the BCH remainder of
                                     // data·x^10 and append it as the 10 check bits (systematic encoding).
    let shifted = data21 << 10; // now a 31-bit word with zero check bits
    let mut rem = shifted;
    for bit in (10..31).rev() {
        if rem & (1 << bit) != 0 {
            rem ^= BCH_POLY << (bit - 10);
        }
    }
    let cw31 = shifted | (rem & 0x3FF);
    (cw31 << 1) | parity_bit(cw31)
}

/// Attempt to correct up to 2 bit errors in a received 32-bit codeword.
///
/// Returns `Some((corrected_codeword, bits_flipped))` if a valid codeword is
/// within Hamming distance 2 (including the parity bit), else `None`.
///
/// Strategy: brute-force syndrome decoding over the 31 protected bits (the
/// parity bit is then recomputed). For BCH(31,21,2) the protected field is 31
/// bits, so 0/1/2-error patterns are 1 + 31 + 31·30/2 = 497 candidates — cheap
/// and exhaustive, giving guaranteed maximum-likelihood correction within the
/// code's distance.
pub fn correct(cw: u32) -> Option<(u32, u32)> {
    // 0 errors.
    if is_valid(cw) {
        return Some((cw, 0));
    }
    // Operate on the 31 protected bits for BCH; reattach parity at the end.
    let base31 = cw >> 1;
    // Single error confined to the parity bit: the protected field is already a
    // valid BCH word (syndrome 0) but overall parity is wrong. Correct by
    // recomputing the parity bit.
    if parity_remainder(cw) == 0 {
        let full = (base31 << 1) | parity_bit(base31);
        return Some((full, (full ^ cw).count_ones()));
    }
    // 1 error in the protected field.
    for i in 0..31 {
        let cand31 = base31 ^ (1 << i);
        if parity_remainder(cand31 << 1) == 0 {
            let full = (cand31 << 1) | parity_bit(cand31);
            // distance from original (protected diff is 1; parity may also flip)
            let flips = (full ^ cw).count_ones();
            return Some((full, flips));
        }
    }
    // 2 errors in the protected field.
    for i in 0..31 {
        for j in (i + 1)..31 {
            let cand31 = base31 ^ (1 << i) ^ (1 << j);
            if parity_remainder(cand31 << 1) == 0 {
                let full = (cand31 << 1) | parity_bit(cand31);
                let flips = (full ^ cw).count_ones();
                return Some((full, flips));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn idle_and_sync_are_valid_codewords() {
        // The idle and sync codewords from ITU-R M.584-2 must satisfy the
        // BCH+parity check by construction (sync is itself a defined codeword).
        assert!(is_valid(IDLE_CODEWORD), "idle codeword must pass BCH+parity");
        // The frame sync codeword is a deliberately chosen 32-bit pattern; it
        // is NOT required to be a valid BCH codeword (it is found by raw bit
        // match, not BCH), so we only assert its value is the spec constant.
        assert_eq!(SYNC_CODEWORD, 0x7CD2_15D8);
    }

    #[test]
    fn encode_produces_valid_codewords() {
        for data in [0x0_0000u32, 0x1_5555, 0x0_AAAA, 0x1F_FFFF, 0x12_3456] {
            let cw = encode(data);
            assert!(is_valid(cw), "encode({data:#x}) -> {cw:#x} invalid");
            // Top 21 bits must equal the data (systematic code).
            assert_eq!(cw >> 11, data & 0x1F_FFFF);
        }
    }

    #[test]
    fn corrects_single_bit_error() {
        let cw = encode(0x12_3456);
        for i in 0..32 {
            let corrupted = cw ^ (1 << i);
            let (fixed, flips) = correct(corrupted).expect("must correct 1 error");
            assert_eq!(fixed, cw, "bit {i}: did not recover original");
            assert_eq!(flips, 1, "bit {i}: expected 1 correction");
        }
    }

    #[test]
    fn corrects_double_bit_error() {
        let cw = encode(0x0A_5C3);
        // A representative double error in the protected field.
        let corrupted = cw ^ (1 << 5) ^ (1 << 20);
        let (fixed, flips) = correct(corrupted).expect("must correct 2 errors");
        assert_eq!(fixed, cw);
        assert_eq!(flips, 2);
    }

    #[test]
    fn rejects_uncorrectable_triple_error() {
        // 3 errors exceed BCH(31,21,2) distance; decoder must not silently
        // "correct" to the wrong codeword for at least some patterns. We assert
        // that it never returns the *original* with flips<=2 (it either fails or
        // mis-corrects to a different codeword, but cannot claim the truth).
        let cw = encode(0x1_2345);
        let corrupted = cw ^ (1 << 1) ^ (1 << 14) ^ (1 << 28);
        if let Some((fixed, flips)) = correct(corrupted) {
            assert!(
                !(fixed == cw && flips <= 2),
                "3-error pattern must not be correctable as the true codeword"
            );
        }
    }
}
