//! Cross-implementation PHY validation: a burst generated by
//! gr-iridium's reference modulator (see tests/data/README.md) must
//! demodulate bit-perfectly — access code recognized and every payload
//! bit satisfying the PRBS15 recurrence.

use num_complex::Complex;
use xng_mode_iridium::{demod::IridiumDemod, frame, CHANNEL_RATE};

#[test]
fn demodulates_gr_iridium_test_burst() {
    let raw = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/grtest_prbs15_250k.i16"
    ))
    .expect("fixture present");
    let mut samples: Vec<Complex<f32>> = raw
        .chunks_exact(4)
        .map(|b| {
            Complex::new(
                i16::from_le_bytes([b[0], b[1]]) as f32 / 32768.0,
                i16::from_le_bytes([b[2], b[3]]) as f32 / 32768.0,
            )
        })
        .collect();
    // Flush margin: the hunt needs max-burst lookahead past the burst.
    samples.extend(
        std::iter::repeat(Complex::new(0.0f32, 0.0)).take((CHANNEL_RATE * 0.15) as usize),
    );

    let mut demod = IridiumDemod::new(CHANNEL_RATE);
    let bursts = demod.process(&samples);
    assert_eq!(bursts.len(), 1, "exactly one burst expected");
    let bits = &bursts[0];
    assert_eq!(&bits[..24], &frame::ACCESS_DL[..], "downlink access code");
    let payload = &bits[24..];
    assert!(payload.len() >= 300, "payload length {}", payload.len());
    let violations = (15..payload.len())
        .filter(|&i| payload[i] != (payload[i - 15] ^ payload[i - 14]))
        .count();
    assert_eq!(violations, 0, "PRBS15 recurrence must hold bit-perfectly");
}
