name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y libsoapysdr-dev libairspy-dev libairspyhf-dev protobuf-compiler
    - name: Build
      run: cargo build --verbose --release --features airspy,airspyhf
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run tests (native Airspy backends)
      run: cargo test --workspace --features airspy,airspyhf --verbose
    - name: Build Debian package
      run: ./build_deb_package.sh
    - uses: actions/upload-artifact@v4
      with:
        name: xng-debian-package-latest
        path: |
          ./build/*.deb
